# Generated by Django 6.0.2 on 2026-03-09 02:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0, message="Narx manfiy bo'lishi mumkin emas")]),
        ),
        migrations.AlterField(
            model_name='product',
            name='price_type',
            field=models.CharField(choices=[('qatiy', 'Qatiy'), ('kelishiladi', 'Kelishiladi'), ('bepul', 'Bepul'), ('ayirboshlash', 'Ayirboshlash')], default='kelishiladi', max_length=30),
        ),
    ]
